version: "2.2"

services:

  redis:
    image: redis:alpine3.12

  web:
    # user: 400:400
    build:
      context: ./services/web/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: "web"
    hostname: "webhost"
    # environment:
    #   fruit: "apple"
    env_file:
      - ./web.env
      - ./mysql.env
    volumes:
      - './services/web/:/usr/src/app/'
# docker run --name mysql -h mysqlhost -e MYSQL_ROOT_PASSWORD="password123" -d mysql:latest
  db:
    build:
       context: ./services/mysql/
      dockerfile: Dockerfile
    ports:
     - 3306:3306
    container_name: "db"
    hostname: "mysqldbhost"
    env_file:
      - ./mysql.env
    volumes:
      - './services/mysql/:/usr/src/app'                                                                   
